version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 80:3000
    networks:
      shopping-list:
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      shopping-list:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    ports:
      - 8080:80
    networks:
      shopping-list:
    depends_on:
      - db

volumes:
  db-data:

networks:
  shopping-list: